/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    customers: CustomerAuthOperations;
    teachers: TeacherAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    customers: Customer;
    teachers: Teacher;
    'session-types': SessionType;
    'session-series': SessionSery;
    sessions: Session;
    bookings: Booking;
    'membership-types': MembershipType;
    memberships: Membership;
    integrations: Integration;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    'session-types': SessionTypesSelect<false> | SessionTypesSelect<true>;
    'session-series': SessionSeriesSelect<false> | SessionSeriesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'membership-types': MembershipTypesSelect<false> | MembershipTypesSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('nl' | 'en') | ('nl' | 'en')[];
  globals: {
    settings: Setting;
    theme: Theme;
    email: Email;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    email: EmailSelect<false> | EmailSelect<true>;
  };
  locale: 'nl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | Customer | Teacher;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface TeacherAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  phone?: string | null;
  dateOfBirth?: string | null;
  membershipStatus?: ('none' | 'trial' | 'active' | 'paused' | 'cancelled') | null;
  /**
   * Internal notes about this customer. Admin-only.
   */
  notes?: string | null;
  /**
   * Set automatically when the customer enters their verification code.
   */
  emailVerified?: boolean | null;
  verificationCode?: string | null;
  verificationExpiresAt?: string | null;
  verificationAttempts?: number | null;
  verificationSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  name: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'teachers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-types".
 */
export interface SessionType {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Color used to tag this type in the schedule.
   */
  color?: string | null;
  /**
   * Drop-in price in eurocents (e.g. 1500 = €15.00). Set to 0 for sessions that are always free.
   */
  priceCents: number;
  /**
   * When checked, active members (and trial members) pay nothing for this session. Drop-ins pay priceCents.
   */
  coveredByMembership?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recurring class templates. Materialize concrete sessions up to the horizon on every save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-series".
 */
export interface SessionSery {
  id: number;
  /**
   * Internal label, e.g. "Mon/Wed Kickboxing 18:00".
   */
  name: string;
  /**
   * Uncheck to stop materializing new sessions. Existing rows are untouched.
   */
  active?: boolean | null;
  type: number | SessionType;
  teacher: number | Teacher;
  /**
   * Optional display title used on each materialized session. Falls back to the type name.
   */
  title?: string | null;
  /**
   * Local time in HH:mm (24h). The gym timezone is Europe/Amsterdam.
   */
  startTime: string;
  durationMinutes: number;
  capacity: number;
  /**
   * Leave empty to use the default location from Site Settings.
   */
  location?: string | null;
  description?: string | null;
  /**
   * Only weekly for now. Monthly/yearly can land later if needed.
   */
  frequency: 'weekly';
  daysOfWeek: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[];
  /**
   * Every N weeks. 1 = every week, 2 = every other week.
   */
  interval?: number | null;
  /**
   * First date the series is allowed to produce a session.
   */
  startsOn: string;
  /**
   * Leave empty for indefinite. Materialization always caps at the horizon.
   */
  endsOn?: string | null;
  /**
   * Dates to skip (holidays, gym closures). Materializer will not create sessions on these days.
   */
  skipDates?:
    | {
        date: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How many weeks ahead to materialize on each save.
   */
  horizonWeeks?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  /**
   * Optional display title. Falls back to the session type name when empty.
   */
  title?: string | null;
  type: number | SessionType;
  teacher: number | Teacher;
  startsAt: string;
  durationMinutes: number;
  capacity: number;
  /**
   * Leave empty to use the default location from Site Settings.
   */
  location?: string | null;
  description?: string | null;
  /**
   * Cancelled sessions are hidden from the public schedule and cannot be booked. Booked customers should be notified manually for now.
   */
  status: 'scheduled' | 'cancelled';
  /**
   * Set automatically when this session is generated from a recurring series.
   */
  series?: (number | null) | SessionSery;
  /**
   * Auto-set to true when an admin edits a series-generated session. The series materializer will then leave this row alone.
   */
  seriesOverride?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  customer: number | Customer;
  session: number | Session;
  status: 'confirmed' | 'cancelled' | 'attended' | 'noshow';
  source: 'web' | 'classpass' | 'manual';
  /**
   * Real payment integration arrives in v2. For now, drop-ins are marked unpaid and settled at the front desk.
   */
  paymentStatus: 'free' | 'credit' | 'unpaid' | 'paid' | 'refunded';
  /**
   * Which membership this booking was charged against (set automatically by the booking flow).
   */
  usedMembership?: (number | null) | Membership;
  /**
   * Number of credits decremented from the linked membership (0 for unlimited).
   */
  creditsUsed?: number | null;
  /**
   * Amount owed for this booking in eurocents. Snapshot of priceCents at booking time.
   */
  amountCents?: number | null;
  /**
   * External provider id (e.g. ClassPass booking id). Set by integrations.
   */
  externalId?: string | null;
  /**
   * Encoded in the QR code the customer shows at the counter.
   */
  checkInCode?: string | null;
  /**
   * Set when staff scan the code and check the customer in.
   */
  checkedInAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  customer: number | Customer;
  type: number | MembershipType;
  status: 'active' | 'paused' | 'expired' | 'cancelled';
  startsAt: string;
  /**
   * Auto-filled from the type's validityDays when blank. Leave empty for no expiry.
   */
  endsAt?: string | null;
  /**
   * Remaining class credits. Auto-seeded from the type on creation for credit packs.
   */
  creditsRemaining?: number | null;
  /**
   * What the customer actually paid for this membership (eurocents).
   */
  paidAmountCents?: number | null;
  /**
   * Mollie/iDEAL/cash reference, etc.
   */
  paymentReference?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-types".
 */
export interface MembershipType {
  id: number;
  name: string;
  /**
   * Stable identifier (e.g. "all-access", "10-strip-card"). Lowercase, hyphens.
   */
  slug: string;
  description?: string | null;
  billingModel: 'unlimited' | 'credits' | 'period';
  /**
   * Purchase price in eurocents (e.g. 12500 = €125,00).
   */
  priceCents: number;
  /**
   * Number of class credits this pack contains.
   */
  creditsIncluded?: number | null;
  /**
   * How many days the membership stays valid after activation. Leave empty for no expiry.
   */
  validityDays?: number | null;
  /**
   * When checked, this membership applies to every session type.
   */
  coversAllTypes?: boolean | null;
  /**
   * Restrict coverage to only these session types.
   */
  includedTypes?: (number | SessionType)[] | null;
  /**
   * Uncheck to hide from new purchases without deleting historical data.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  name: string;
  provider: 'classpass' | 'custom';
  enabled?: boolean | null;
  /**
   * Provider-specific configuration (API keys, studio id, etc.). Stored as JSON.
   */
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastSyncAt?: string | null;
  lastSyncStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'teachers';
        value: number | Teacher;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  dateOfBirth?: T;
  membershipStatus?: T;
  notes?: T;
  emailVerified?: T;
  verificationCode?: T;
  verificationExpiresAt?: T;
  verificationAttempts?: T;
  verificationSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  avatar?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-types_select".
 */
export interface SessionTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  priceCents?: T;
  coveredByMembership?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-series_select".
 */
export interface SessionSeriesSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  type?: T;
  teacher?: T;
  title?: T;
  startTime?: T;
  durationMinutes?: T;
  capacity?: T;
  location?: T;
  description?: T;
  frequency?: T;
  daysOfWeek?: T;
  interval?: T;
  startsOn?: T;
  endsOn?: T;
  skipDates?:
    | T
    | {
        date?: T;
        reason?: T;
        id?: T;
      };
  horizonWeeks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  teacher?: T;
  startsAt?: T;
  durationMinutes?: T;
  capacity?: T;
  location?: T;
  description?: T;
  status?: T;
  series?: T;
  seriesOverride?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  customer?: T;
  session?: T;
  status?: T;
  source?: T;
  paymentStatus?: T;
  usedMembership?: T;
  creditsUsed?: T;
  amountCents?: T;
  externalId?: T;
  checkInCode?: T;
  checkedInAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-types_select".
 */
export interface MembershipTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  billingModel?: T;
  priceCents?: T;
  creditsIncluded?: T;
  validityDays?: T;
  coversAllTypes?: T;
  includedTypes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  customer?: T;
  type?: T;
  status?: T;
  startsAt?: T;
  endsAt?: T;
  creditsRemaining?: T;
  paidAmountCents?: T;
  paymentReference?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  enabled?: T;
  config?: T;
  lastSyncAt?: T;
  lastSyncStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Shown in the site header, footer, contact and about pages, and in emails.
   */
  gym: {
    name: string;
    /**
     * One line under the name in search results and link previews.
     */
    tagline?: string | null;
    /**
     * The body of the About page.
     */
    about?: string | null;
    contactEmail?: string | null;
    contactPhone?: string | null;
    address?: string | null;
    /**
     * Where classes take place unless a class says otherwise. Empty: the gym name is used.
     */
    defaultLocation?: string | null;
    /**
     * Link to your privacy policy. The footer link only shows when set.
     */
    privacyUrl?: string | null;
    /**
     * Link to your terms. The footer link only shows when set.
     */
    termsUrl?: string | null;
  };
  /**
   * These hours determine the time range shown on the public schedule grid.
   */
  openingHours?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        closed?: boolean | null;
        /**
         * HH:mm (24h)
         */
        open?: string | null;
        /**
         * HH:mm (24h)
         */
        close?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Sessions that have already finished.
   */
  scheduleSessionPast?: string | null;
  /**
   * Upcoming sessions the viewer can still book.
   */
  scheduleSessionFuture?: string | null;
  /**
   * Upcoming sessions the signed-in customer has already booked.
   */
  scheduleSessionBooked?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Transactional email provider used for signup verification and booking confirmations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email".
 */
export interface Email {
  id: number;
  /**
   * Which HTTPS email API to use. Only Resend is wired up today.
   */
  provider: 'resend' | 'sendgrid';
  /**
   * Verified sender, e.g. "Your Gym <hello@mail.example.com>". Must match a verified domain in the provider.
   */
  fromAddress?: string | null;
  /**
   * Stored in the database in plain text. Treat the admin panel as sensitive.
   */
  apiKey?: string | null;
  /**
   * When enabled, new customers receive a 6-digit code by email and must enter it before they can book. Can only be enabled once both From address and API key are filled in.
   */
  verificationRequired?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  gym?:
    | T
    | {
        name?: T;
        tagline?: T;
        about?: T;
        contactEmail?: T;
        contactPhone?: T;
        address?: T;
        defaultLocation?: T;
        privacyUrl?: T;
        termsUrl?: T;
      };
  openingHours?:
    | T
    | {
        day?: T;
        closed?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  scheduleSessionPast?: T;
  scheduleSessionFuture?: T;
  scheduleSessionBooked?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_select".
 */
export interface EmailSelect<T extends boolean = true> {
  provider?: T;
  fromAddress?: T;
  apiKey?: T;
  verificationRequired?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}